export const ALL_MENTOR_NAMES = [
  "JULIE", "MARK", "JAMES", "DOC", "TECHGUY", "SIGMA", "CIPHER", "RICK",
  "ALEX", "PAUL", "PAT", "ULYSES", "ATK", "DEF", "SCOUT", "RAY",
  "KAREN", "WATCHER", "MAILMAN", "JERRY", "THAT GUY",
];

export const FALLBACK_MENTOR_NAMES = ALL_MENTOR_NAMES;
